spring:
  application:
    name: coze-video-api
  servlet:
    multipart:
      enabled: true
      max-file-size: 512MB
      max-request-size: 512MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql:3306/ai_ecommerce_saas?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/ai_ecommerce_saas?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5

  data:
    redis:
#      host: ${REDIS_HOST:redis}
#      port: ${REDIS_PORT:6379}
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha


server:
  port: 8088

coze:
  token: pat_2jDBZ9194UbpAI9MykYgCBX4OrGxDa7vR5BAR1RMCcPC9zERVsrBLyRnTSpeJ77K
  base-url: https://api.coze.cn
  workflow-id: "7621433301101887522"
  copywriting-workflow-id: "7620722682200358922"
  timeout-minutes: 20

kling:
  access-key: "AKFJ4PFmhLFM8GPtTRDDapyPfge4nfgt"
  secret-key: "CetkPkePtTJKEkypdQ8HAfNMJe9YAYek"
  base-url: "https://api-beijing.klingai.com/v1/videos/omni-video"
  token-expire-seconds: 1800

wechat:
  miniapp:
    # 小程序AppID（请替换为实际的小程序AppID）
    appid: ${WECHAT_APPID:wxb6e73136954c2093}
    # 小程序AppSecret（请替换为实际的小程序AppSecret）
    secret: ${WECHAT_SECRET:4dfaf365395a557a38614516926fc027}
  pay:
    # 小程序AppID
    app-id: ${WECHAT_APPID:wxb6e73136954c2093}
    # 商户号
    mch-id: 779068919
    # 商户API密钥
    api-key: your_api_key_here
    # 支付结果通知地址(需要替换为实际的外网可访问地址)
    notify-url: https://your-domain.com/api/payment/notify
    # 交易类型: JSAPI-小程序支付
    trade-type: JSAPI

jwt:
  # JWT密钥（请替换为实际的安全密钥）
  secret: 8f3hG@9kL#2mN$5pQ^7rT&1vW*yXzB4cD6eF
  # Token过期时间（毫秒），7天 = 604800000
  expire: 604800000

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0