spring:
  application:
    name: coze-video-api
  servlet:
    multipart:
      enabled: true
      max-file-size: 512MB
      max-request-size: 512MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql:3306/ai_ecommerce_saas?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/ai_ecommerce_saas?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5

  data:
    redis:
#      host: ${REDIS_HOST:redis}
#      port: ${REDIS_PORT:6379}
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

server:
  port: 8088

coze:
  token: pat_BCVIs2dfos4sM6xfDeltCNZEgbp2aOyP82DkLzEKgjMM6UjC7L2hXsmkG0qx9cjE
  base-url: https://api.coze.cn
  workflow-id: "7621433301101887522"
  copywriting-workflow-id: "7620722682200358922"
  timeout-minutes: 10

kling:
  access-key: "AKFJ4PFmhLFM8GPtTRDDapyPfge4nfgt"
  secret-key: "CetkPkePtTJKEkypdQ8HAfNMJe9YAYek"
  base-url: "https://api-beijing.klingai.com/v1/videos/omni-video"
  token-expire-seconds: 1800

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0